name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux:
    name: ${{ matrix.os }}.${{ matrix.compiler.compiler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ linux ]
        compiler:
          - { compiler: GNU,  CC: gcc,   CXX: g++,     GCOV: gcov }
          - { compiler: LLVM, CC: clang, CXX: clang++ }

    steps:
    - uses: actions/checkout@v3


    - name: install packages
      run: |
       sudo apt-get update -y
       sudo apt-get install -y googletest zlib1g-dev clang++-12 g++ cmake

    - name: install google test
      run: |
       cd /usr/src/googletest
       sudo cmake -DCMAKE_CXX_COMPILER=$CXX .
       sudo make
       sudo make install
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
        GCOV: ${{ matrix.compiler.GCOV }}
       
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=$CXX
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
        GCOV: ${{ matrix.compiler.GCOV }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
        GCOV: ${{ matrix.compiler.GCOV }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
        GCOV: ${{ matrix.compiler.GCOV }}
